修改部分接口信息
Kp-kj/taskManager-Service pull request #7
Opened 2023-06-28 02:25 UTC by mangosteenLi

2023-06-28 02:41 UTC, China-Chris requested changes
感谢提交，请处理一些杂事

2023-06-28 02:41 UTC, China-Chris commented on task/etc/task.yaml
>    DataSource: root:123456@tcp(localhost:3306)/adfi?charset=utf8&parseTime=True&loc=Local
将这里配置成 阿里云的数据库吧，线上用不了本地的数据库

2023-06-28 02:41 UTC, China-Chris commented on task/logs/access.log
> +2023-06-28T00:00:32.555+08:00	[34;1m info [0m	compressing log file: logs/access.log-2023-06-27	caller=logx/rotatelogger.go:408
可以将日志清理一下，我好像写了个git的忽略文件去做这件事，但我那边应该也有做。日志文件清理一下在传上来吧  这样会让打包成的文件小一点。我之后也会做这事情。

2023-06-28 02:43 UTC, China-Chris commented
之后发起审核请填写下 受让人和审核人哈。

2023-06-28 02:45 UTC, wangshijia612 commented
好的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月28日 10:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Kp-kj/taskManager-Service] 修改部分接口信息 (PR #7) |

之后发起审核请填写下 受让人和审核人哈。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were assigned.Message ID: ***@***.***>

2023-06-28 08:54 UTC, China-Chris commented
@mangosteenLi   由于分支目录结构已经修改。该提交按照最新目录结构修改业务后提交 感谢提交

2023-06-29 05:15 UTC, China-Chris commented
@mangosteenLi  已审核 请自行合并

2023-06-29 07:13 UTC, China-Chris approved these changes

2023-06-30 08:28 UTC, closed without merging